# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290e92c935326513ddbd7cc4477ee36b6c653df5cfbf0fab9792402f5b73e61c7b66231930179b01c5bafde7d8a1df6943ea8f9e1997d530991ee74e69d0aba4

test:
  secret_key_base: 74a2e72b7f983105b08d8e3f180968d4a56d8441a9bee8f730a45019ad80e93289e6a6a468e34618fe5cde83be9d528214bffb152d52f2cd30095c7080aff448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
